[package]
name = "libkatatsuki-sys"
version = "1.0.5"
authors = ["Ronny Chan <ronny6993@gmail.com>"]
links = "libkatatsuki"
description = "Rust bindings for the Track interface of katatsuki"
license = "MIT"

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1"
bindgen = "0.26.3"