[package]
name = "seiri-core"
version = "0.1.0"
authors = ["Ronny Chan <ronny@ronnchyran.com>"]

[dependencies]
notify = "4.0.3"

[dependencies.taglib]
path = "deps/taglib-rust"
features = ["use-vcpkg"]

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled"]