[package]
name = "seiri-watcher"
version = "0.1.0"
authors = ["Ronny Chan <ronny@ronnchyran.com>"]
include = ["tools/**/*"]

[dependencies]
#seiri = "0"
notify = "4.0.3"
rand = "0.4.2"
walkdir = "2"
rayon = { version = "1.0", optional = true }
rocket =  { version = "0.3.8", optional = true }
juniper = { version = "0.9.2", optional = true }
juniper_codegen = { version = "0.9.2", optional = true }
juniper_rocket = { version = "0.1.2", optiona = true }
rocket_cors = { version = "0.2.1", optional = true }

[dependencies.seiri]
path = "../seiri-lib"
[features]
default = []
use_graphql = [
    "rocket_cors",
    "rayon",
    "juniper",
    "juniper_codegen",
    "rocket"
]



[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled", "functions"]
