[package]
name = "seiri-watcher"
version = "0.1.0"
authors = ["Ronny Chan <ronny@ronnchyran.com>"]
include = ["tools/**/*"]

[dependencies]
#seiri = "0"
notify = "4.0.3"
rand = "0.4.2"
walkdir = "2"
seiri = "0.6.2"

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled", "functions"]
